// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bears/fields.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type FieldRows struct {
	Columns []Tiles `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns"`
}

func (m *FieldRows) Reset()         { *m = FieldRows{} }
func (m *FieldRows) String() string { return proto.CompactTextString(m) }
func (*FieldRows) ProtoMessage()    {}
func (*FieldRows) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb33884978356795, []int{0}
}
func (m *FieldRows) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FieldRows) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FieldRows.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FieldRows) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldRows.Merge(m, src)
}
func (m *FieldRows) XXX_Size() int {
	return m.Size()
}
func (m *FieldRows) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldRows.DiscardUnknown(m)
}

var xxx_messageInfo_FieldRows proto.InternalMessageInfo

func (m *FieldRows) GetColumns() []Tiles {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ItemPosition struct {
	FieldId  uint64 `protobuf:"varint,1,opt,name=fieldId,proto3" json:"fieldId,omitempty"`
	RowId    uint64 `protobuf:"varint,2,opt,name=rowId,proto3" json:"rowId,omitempty"`
	ColumnId uint64 `protobuf:"varint,3,opt,name=columnId,proto3" json:"columnId,omitempty"`
}

func (m *ItemPosition) Reset()         { *m = ItemPosition{} }
func (m *ItemPosition) String() string { return proto.CompactTextString(m) }
func (*ItemPosition) ProtoMessage()    {}
func (*ItemPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb33884978356795, []int{1}
}
func (m *ItemPosition) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ItemPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ItemPosition.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ItemPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemPosition.Merge(m, src)
}
func (m *ItemPosition) XXX_Size() int {
	return m.Size()
}
func (m *ItemPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemPosition.DiscardUnknown(m)
}

var xxx_messageInfo_ItemPosition proto.InternalMessageInfo

func (m *ItemPosition) GetFieldId() uint64 {
	if m != nil {
		return m.FieldId
	}
	return 0
}

func (m *ItemPosition) GetRowId() uint64 {
	if m != nil {
		return m.RowId
	}
	return 0
}

func (m *ItemPosition) GetColumnId() uint64 {
	if m != nil {
		return m.ColumnId
	}
	return 0
}

type FieldParams struct {
	FieldType string                                   `protobuf:"bytes,1,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty" yaml:"field_type"`
	Fertility github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,2,opt,name=fertility,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"fertility" yaml:"fertility"`
	PriceTile github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=price_tile,json=priceTile,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"price_tile" yaml:"price_tile"`
}

func (m *FieldParams) Reset()         { *m = FieldParams{} }
func (m *FieldParams) String() string { return proto.CompactTextString(m) }
func (*FieldParams) ProtoMessage()    {}
func (*FieldParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb33884978356795, []int{2}
}
func (m *FieldParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FieldParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FieldParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FieldParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldParams.Merge(m, src)
}
func (m *FieldParams) XXX_Size() int {
	return m.Size()
}
func (m *FieldParams) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldParams.DiscardUnknown(m)
}

var xxx_messageInfo_FieldParams proto.InternalMessageInfo

func (m *FieldParams) GetFieldType() string {
	if m != nil {
		return m.FieldType
	}
	return ""
}

func (m *FieldParams) GetPriceTile() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.PriceTile
	}
	return nil
}

type Fields struct {
	Id         uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BearOwner  *BearOwner   `protobuf:"bytes,2,opt,name=bearOwner,proto3" json:"bearOwner,omitempty"`
	Params     *FieldParams `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	Rows       []FieldRows  `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows"`
	CountTiles uint64       `protobuf:"varint,5,opt,name=countTiles,proto3" json:"countTiles,omitempty"`
}

func (m *Fields) Reset()         { *m = Fields{} }
func (m *Fields) String() string { return proto.CompactTextString(m) }
func (*Fields) ProtoMessage()    {}
func (*Fields) Descriptor() ([]byte, []int) {
	return fileDescriptor_fb33884978356795, []int{3}
}
func (m *Fields) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fields) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fields.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fields) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fields.Merge(m, src)
}
func (m *Fields) XXX_Size() int {
	return m.Size()
}
func (m *Fields) XXX_DiscardUnknown() {
	xxx_messageInfo_Fields.DiscardUnknown(m)
}

var xxx_messageInfo_Fields proto.InternalMessageInfo

func (m *Fields) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Fields) GetBearOwner() *BearOwner {
	if m != nil {
		return m.BearOwner
	}
	return nil
}

func (m *Fields) GetParams() *FieldParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *Fields) GetRows() []FieldRows {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *Fields) GetCountTiles() uint64 {
	if m != nil {
		return m.CountTiles
	}
	return 0
}

func init() {
	proto.RegisterType((*FieldRows)(nil), "MonetaToday.honeywood.bears.FieldRows")
	proto.RegisterType((*ItemPosition)(nil), "MonetaToday.honeywood.bears.ItemPosition")
	proto.RegisterType((*FieldParams)(nil), "MonetaToday.honeywood.bears.FieldParams")
	proto.RegisterType((*Fields)(nil), "MonetaToday.honeywood.bears.Fields")
}

func init() { proto.RegisterFile("bears/fields.proto", fileDescriptor_fb33884978356795) }

var fileDescriptor_fb33884978356795 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x8d, 0xd3, 0x34, 0xc5, 0x1b, 0x84, 0xe8, 0xaa, 0x48, 0x26, 0x48, 0x4e, 0xe5, 0x43, 0x94,
	0x0b, 0xbb, 0x6a, 0xe0, 0xc4, 0xa9, 0x32, 0x05, 0x35, 0x07, 0xd4, 0xca, 0x8a, 0x84, 0xd4, 0x4b,
	0x71, 0xec, 0x6d, 0xba, 0x22, 0xf6, 0x44, 0xde, 0x0d, 0xc1, 0x27, 0x24, 0xbe, 0x80, 0xaf, 0xe0,
	0xc0, 0x97, 0xf4, 0xd8, 0x23, 0xe2, 0x10, 0x50, 0xf2, 0x07, 0xfd, 0x02, 0xb4, 0x63, 0x9b, 0x84,
	0x4b, 0xe0, 0x62, 0xef, 0xcc, 0xee, 0x7b, 0x33, 0xf3, 0xde, 0x2e, 0xa1, 0x23, 0x11, 0x66, 0x8a,
	0x5f, 0x49, 0x31, 0x89, 0x15, 0x9b, 0x66, 0xa0, 0x81, 0x3e, 0x79, 0x03, 0xa9, 0xd0, 0xe1, 0x10,
	0xe2, 0x30, 0x67, 0xd7, 0x90, 0x8a, 0x7c, 0x0e, 0x10, 0x33, 0x3c, 0xd9, 0x76, 0x23, 0x50, 0x09,
	0x28, 0x3e, 0x0a, 0x95, 0xe0, 0x1f, 0x8e, 0x46, 0x42, 0x87, 0x47, 0x3c, 0x02, 0x99, 0x16, 0xe0,
	0xf6, 0xc1, 0x18, 0xc6, 0x80, 0x4b, 0x6e, 0x56, 0x65, 0x76, 0xbf, 0x28, 0xa3, 0xe5, 0x44, 0xa8,
	0xbf, 0x53, 0xf8, 0x2d, 0x52, 0xde, 0x19, 0xb1, 0x5f, 0x9b, 0x46, 0x02, 0x98, 0x2b, 0xea, 0x93,
	0xbd, 0x08, 0x26, 0xb3, 0x24, 0x55, 0x8e, 0x75, 0xb8, 0xd3, 0x6b, 0xf5, 0x3d, 0xb6, 0xa5, 0x2f,
	0x36, 0x34, 0xd4, 0x7e, 0xe3, 0x66, 0xd1, 0xa9, 0x05, 0x15, 0xd0, 0xbb, 0x20, 0xf7, 0x07, 0x5a,
	0x24, 0xe7, 0xa0, 0xa4, 0x96, 0x90, 0x52, 0x87, 0xec, 0xe1, 0xa4, 0x83, 0xd8, 0xb1, 0x0e, 0xad,
	0x5e, 0x23, 0xa8, 0x42, 0x7a, 0x40, 0x76, 0x33, 0x98, 0x0f, 0x62, 0xa7, 0x8e, 0xf9, 0x22, 0xa0,
	0x6d, 0x72, 0xaf, 0xa0, 0x1a, 0xc4, 0xce, 0x0e, 0x6e, 0xfc, 0x89, 0xbd, 0xaf, 0x75, 0xd2, 0xc2,
	0x6e, 0xcf, 0xc3, 0x2c, 0x4c, 0x14, 0x7d, 0x4e, 0x08, 0x92, 0x5d, 0xea, 0x7c, 0x2a, 0x90, 0xde,
	0xf6, 0x1f, 0xdd, 0x2d, 0x3a, 0xfb, 0x79, 0x98, 0x4c, 0x5e, 0x78, 0xeb, 0x3d, 0x2f, 0xb0, 0x31,
	0x18, 0xe6, 0x53, 0x41, 0xdf, 0x11, 0xfb, 0x4a, 0x64, 0x5a, 0x4e, 0xa4, 0xce, 0xb1, 0xb6, 0xed,
	0xfb, 0x66, 0x86, 0x1f, 0x8b, 0x4e, 0x77, 0x2c, 0xf5, 0xf5, 0x6c, 0xc4, 0x22, 0x48, 0x78, 0x29,
	0x7a, 0xf1, 0x7b, 0xaa, 0xe2, 0xf7, 0xdc, 0x30, 0x29, 0x76, 0x22, 0xa2, 0xbb, 0x45, 0xe7, 0x61,
	0x59, 0xa2, 0x22, 0x32, 0x15, 0xaa, 0x35, 0xfd, 0x44, 0xc8, 0x34, 0x93, 0x91, 0xb8, 0x34, 0xe2,
	0x3b, 0x3b, 0x28, 0xe5, 0x63, 0x56, 0x30, 0x31, 0xe3, 0x22, 0x2b, 0x5d, 0x64, 0x2f, 0x41, 0xa6,
	0xfe, 0x2b, 0x53, 0x7d, 0xdd, 0xf6, 0x1a, 0xea, 0x7d, 0xfb, 0xd9, 0xe9, 0xfd, 0x47, 0x4b, 0x86,
	0x45, 0x05, 0x36, 0x02, 0x8d, 0x29, 0xde, 0xe7, 0x3a, 0x69, 0xa2, 0x50, 0x8a, 0x3e, 0x20, 0x75,
	0x59, 0x49, 0x5f, 0x97, 0x31, 0x3d, 0x21, 0xb6, 0x71, 0xef, 0x6c, 0x9e, 0x8a, 0x0c, 0xa7, 0x6f,
	0xf5, 0xbb, 0x5b, 0x5d, 0xf6, 0xab, 0xd3, 0xc1, 0x1a, 0x48, 0x8f, 0x49, 0x73, 0x8a, 0x1e, 0xa0,
	0x47, 0xad, 0x7e, 0x6f, 0x2b, 0xc5, 0x86, 0x67, 0x41, 0x89, 0xa3, 0xc7, 0xa4, 0x91, 0xc1, 0x5c,
	0x39, 0x0d, 0x54, 0xa7, 0xfb, 0x6f, 0xbc, 0xb9, 0xa1, 0xe5, 0x65, 0x43, 0x24, 0x75, 0x09, 0x89,
	0x60, 0x96, 0x6a, 0xbc, 0x86, 0xce, 0x2e, 0x4e, 0xb8, 0x91, 0xf1, 0x4f, 0x6f, 0x96, 0xae, 0x75,
	0xbb, 0x74, 0xad, 0x5f, 0x4b, 0xd7, 0xfa, 0xb2, 0x72, 0x6b, 0xb7, 0x2b, 0xb7, 0xf6, 0x7d, 0xe5,
	0xd6, 0x2e, 0xd8, 0x86, 0xa6, 0x1b, 0x75, 0xf9, 0xa9, 0xa9, 0xfb, 0x16, 0x20, 0xe6, 0x1f, 0x79,
	0xf9, 0x7a, 0x8c, 0xbe, 0xa3, 0x26, 0xbe, 0x95, 0x67, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x17, 0x37, 0x2e, 0xba, 0x03, 0x00, 0x00,
}

func (m *FieldRows) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldRows) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FieldRows) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Columns) > 0 {
		for iNdEx := len(m.Columns) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Columns[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFields(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ItemPosition) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ItemPosition) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ItemPosition) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ColumnId != 0 {
		i = encodeVarintFields(dAtA, i, uint64(m.ColumnId))
		i--
		dAtA[i] = 0x18
	}
	if m.RowId != 0 {
		i = encodeVarintFields(dAtA, i, uint64(m.RowId))
		i--
		dAtA[i] = 0x10
	}
	if m.FieldId != 0 {
		i = encodeVarintFields(dAtA, i, uint64(m.FieldId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FieldParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FieldParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FieldParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PriceTile) > 0 {
		for iNdEx := len(m.PriceTile) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PriceTile[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFields(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	{
		size := m.Fertility.Size()
		i -= size
		if _, err := m.Fertility.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintFields(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.FieldType) > 0 {
		i -= len(m.FieldType)
		copy(dAtA[i:], m.FieldType)
		i = encodeVarintFields(dAtA, i, uint64(len(m.FieldType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Fields) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fields) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fields) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CountTiles != 0 {
		i = encodeVarintFields(dAtA, i, uint64(m.CountTiles))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Rows) > 0 {
		for iNdEx := len(m.Rows) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rows[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintFields(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFields(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BearOwner != nil {
		{
			size, err := m.BearOwner.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFields(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintFields(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintFields(dAtA []byte, offset int, v uint64) int {
	offset -= sovFields(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *FieldRows) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Columns) > 0 {
		for _, e := range m.Columns {
			l = e.Size()
			n += 1 + l + sovFields(uint64(l))
		}
	}
	return n
}

func (m *ItemPosition) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FieldId != 0 {
		n += 1 + sovFields(uint64(m.FieldId))
	}
	if m.RowId != 0 {
		n += 1 + sovFields(uint64(m.RowId))
	}
	if m.ColumnId != 0 {
		n += 1 + sovFields(uint64(m.ColumnId))
	}
	return n
}

func (m *FieldParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FieldType)
	if l > 0 {
		n += 1 + l + sovFields(uint64(l))
	}
	l = m.Fertility.Size()
	n += 1 + l + sovFields(uint64(l))
	if len(m.PriceTile) > 0 {
		for _, e := range m.PriceTile {
			l = e.Size()
			n += 1 + l + sovFields(uint64(l))
		}
	}
	return n
}

func (m *Fields) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFields(uint64(m.Id))
	}
	if m.BearOwner != nil {
		l = m.BearOwner.Size()
		n += 1 + l + sovFields(uint64(l))
	}
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovFields(uint64(l))
	}
	if len(m.Rows) > 0 {
		for _, e := range m.Rows {
			l = e.Size()
			n += 1 + l + sovFields(uint64(l))
		}
	}
	if m.CountTiles != 0 {
		n += 1 + sovFields(uint64(m.CountTiles))
	}
	return n
}

func sovFields(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFields(x uint64) (n int) {
	return sovFields(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *FieldRows) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFields
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldRows: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldRows: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Columns", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Columns = append(m.Columns, Tiles{})
			if err := m.Columns[len(m.Columns)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFields(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFields
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ItemPosition) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFields
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ItemPosition: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ItemPosition: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldId", wireType)
			}
			m.FieldId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FieldId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RowId", wireType)
			}
			m.RowId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RowId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ColumnId", wireType)
			}
			m.ColumnId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ColumnId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFields(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFields
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FieldParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFields
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FieldParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FieldParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FieldType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fertility", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fertility.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceTile", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceTile = append(m.PriceTile, types.Coin{})
			if err := m.PriceTile[len(m.PriceTile)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFields(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFields
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fields) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFields
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fields: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fields: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BearOwner", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BearOwner == nil {
				m.BearOwner = &BearOwner{}
			}
			if err := m.BearOwner.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &FieldParams{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rows", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFields
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFields
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rows = append(m.Rows, FieldRows{})
			if err := m.Rows[len(m.Rows)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountTiles", wireType)
			}
			m.CountTiles = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFields
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountTiles |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFields(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFields
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFields(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFields
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFields
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFields
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFields
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFields
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFields
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFields        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFields          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFields = fmt.Errorf("proto: unexpected end of group")
)
