// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bears/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the bears module's genesis state.
type GenesisState struct {
	Params           Params         `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	BearNamesList    []BearNames    `protobuf:"bytes,2,rep,name=bearNamesList,proto3" json:"bearNamesList"`
	BearsList        []Bears        `protobuf:"bytes,3,rep,name=bearsList,proto3" json:"bearsList"`
	BearsCount       uint64         `protobuf:"varint,4,opt,name=bearsCount,proto3" json:"bearsCount,omitempty"`
	AddressBearsList []AddressBears `protobuf:"bytes,5,rep,name=addressBearsList,proto3" json:"addressBearsList"`
	FieldsList       []Fields       `protobuf:"bytes,6,rep,name=fieldsList,proto3" json:"fieldsList"`
	FieldsCount      uint64         `protobuf:"varint,7,opt,name=fieldsCount,proto3" json:"fieldsCount,omitempty"`
	TreesList        []Trees        `protobuf:"bytes,8,rep,name=treesList,proto3" json:"treesList"`
	TreesCount       uint64         `protobuf:"varint,9,opt,name=treesCount,proto3" json:"treesCount,omitempty"`
	DecorationsList  []Decorations  `protobuf:"bytes,10,rep,name=decorationsList,proto3" json:"decorationsList"`
	DecorationsCount uint64         `protobuf:"varint,11,opt,name=decorationsCount,proto3" json:"decorationsCount,omitempty"`
	ApiariesList     []Apiaries     `protobuf:"bytes,12,rep,name=apiariesList,proto3" json:"apiariesList"`
	ApiariesCount    uint64         `protobuf:"varint,13,opt,name=apiariesCount,proto3" json:"apiariesCount,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2033069489f775d2, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetBearNamesList() []BearNames {
	if m != nil {
		return m.BearNamesList
	}
	return nil
}

func (m *GenesisState) GetBearsList() []Bears {
	if m != nil {
		return m.BearsList
	}
	return nil
}

func (m *GenesisState) GetBearsCount() uint64 {
	if m != nil {
		return m.BearsCount
	}
	return 0
}

func (m *GenesisState) GetAddressBearsList() []AddressBears {
	if m != nil {
		return m.AddressBearsList
	}
	return nil
}

func (m *GenesisState) GetFieldsList() []Fields {
	if m != nil {
		return m.FieldsList
	}
	return nil
}

func (m *GenesisState) GetFieldsCount() uint64 {
	if m != nil {
		return m.FieldsCount
	}
	return 0
}

func (m *GenesisState) GetTreesList() []Trees {
	if m != nil {
		return m.TreesList
	}
	return nil
}

func (m *GenesisState) GetTreesCount() uint64 {
	if m != nil {
		return m.TreesCount
	}
	return 0
}

func (m *GenesisState) GetDecorationsList() []Decorations {
	if m != nil {
		return m.DecorationsList
	}
	return nil
}

func (m *GenesisState) GetDecorationsCount() uint64 {
	if m != nil {
		return m.DecorationsCount
	}
	return 0
}

func (m *GenesisState) GetApiariesList() []Apiaries {
	if m != nil {
		return m.ApiariesList
	}
	return nil
}

func (m *GenesisState) GetApiariesCount() uint64 {
	if m != nil {
		return m.ApiariesCount
	}
	return 0
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "MonetaToday.honeywood.bears.GenesisState")
}

func init() { proto.RegisterFile("bears/genesis.proto", fileDescriptor_2033069489f775d2) }

var fileDescriptor_2033069489f775d2 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0x13, 0x56, 0x02, 0x3b, 0x69, 0xc5, 0x30, 0x13, 0x94, 0x22, 0x85, 0x68, 0xfc, 0x51,
	0xe0, 0x22, 0x91, 0xc6, 0x13, 0x2c, 0xa0, 0x31, 0x24, 0xfe, 0xa9, 0x4c, 0x02, 0xc1, 0xc5, 0xe4,
	0x2e, 0x26, 0x8b, 0x44, 0xe3, 0x28, 0xf1, 0x04, 0x7d, 0x0b, 0x1e, 0x88, 0x07, 0xd8, 0xe5, 0x2e,
	0xb9, 0x42, 0xa8, 0x7d, 0x11, 0xe4, 0x63, 0xbb, 0x71, 0x57, 0x29, 0xec, 0xa6, 0xaa, 0x3f, 0x9f,
	0xef, 0xf7, 0x1d, 0x9f, 0xd8, 0x70, 0x6b, 0xc2, 0x68, 0xdd, 0x24, 0x39, 0x2b, 0x59, 0x53, 0x34,
	0x71, 0x55, 0x73, 0xc1, 0xc9, 0xbd, 0x37, 0xbc, 0x64, 0x82, 0x1e, 0xf2, 0x8c, 0xce, 0xe2, 0x13,
	0x5e, 0xb2, 0xd9, 0x77, 0xce, 0xb3, 0x18, 0x4b, 0x47, 0xdb, 0x39, 0xcf, 0x39, 0xd6, 0x25, 0xf2,
	0x9f, 0xb2, 0x8c, 0x88, 0xe2, 0x54, 0xb4, 0xa6, 0x53, 0x8d, 0x19, 0xdd, 0x56, 0x9a, 0xfc, 0x3d,
	0x2a, 0xe9, 0x94, 0x19, 0xfd, 0x66, 0xab, 0x1b, 0xe9, 0xae, 0x92, 0x68, 0x96, 0xd5, 0xac, 0x69,
	0x8e, 0xec, 0x2d, 0x4d, 0xfe, 0x5a, 0xb0, 0x6f, 0xd9, 0x05, 0x82, 0xa8, 0xd9, 0x12, 0x7a, 0x47,
	0x49, 0x19, 0x3b, 0xe6, 0x35, 0x15, 0x05, 0x2f, 0xcd, 0xc6, 0xb6, 0x46, 0x57, 0x05, 0xad, 0x0b,
	0x53, 0xbe, 0xf3, 0xcb, 0x83, 0xfe, 0x4b, 0x75, 0xe8, 0x0f, 0x82, 0x0a, 0x46, 0xf6, 0xc0, 0x53,
	0xcd, 0x0f, 0xdd, 0xd0, 0x8d, 0xfc, 0xdd, 0x07, 0x71, 0xc7, 0x10, 0xe2, 0xf7, 0x58, 0x9a, 0xf6,
	0xce, 0xfe, 0xdc, 0x77, 0xc6, 0xda, 0x48, 0xc6, 0x30, 0x90, 0xbb, 0x6f, 0xe5, 0x51, 0x5f, 0x17,
	0x8d, 0x18, 0x5e, 0x09, 0x37, 0x22, 0x7f, 0xf7, 0x71, 0x27, 0x29, 0x35, 0x0e, 0x0d, 0x5b, 0x45,
	0x90, 0x7d, 0xd8, 0xc4, 0x3a, 0xe4, 0x6d, 0x20, 0x6f, 0xe7, 0xbf, 0x3c, 0xc3, 0x6a, 0xad, 0x24,
	0x00, 0xc0, 0xc5, 0x73, 0x7e, 0x5a, 0x8a, 0x61, 0x2f, 0x74, 0xa3, 0xde, 0xd8, 0x52, 0xc8, 0x17,
	0xd8, 0xd2, 0xc3, 0x4f, 0x97, 0x71, 0x57, 0x31, 0xee, 0x49, 0x67, 0xdc, 0x9e, 0x65, 0xd2, 0xa9,
	0x6b, 0x20, 0xf2, 0x0a, 0x40, 0x7d, 0x3e, 0xc4, 0x7a, 0x88, 0xed, 0x9e, 0xef, 0x3e, 0x96, 0x6b,
	0xa0, 0x65, 0x26, 0x21, 0xf8, 0x6a, 0xa5, 0x0e, 0x72, 0x0d, 0x0f, 0x62, 0x4b, 0x72, 0x62, 0x78,
	0x2f, 0x30, 0xeb, 0xfa, 0x25, 0x26, 0x76, 0x28, 0xab, 0xcd, 0xc4, 0x96, 0x56, 0x39, 0x31, 0x5c,
	0xa8, 0xa0, 0x4d, 0x35, 0xb1, 0x56, 0x21, 0x9f, 0xe0, 0x86, 0x75, 0xd9, 0x30, 0x0d, 0x30, 0x2d,
	0xea, 0x4c, 0x7b, 0xd1, 0x7a, 0x74, 0xe6, 0x45, 0x0c, 0x79, 0x0a, 0x5b, 0x96, 0xa4, 0xf2, 0x7d,
	0xcc, 0x5f, 0xd3, 0xc9, 0x3b, 0xe8, 0x9b, 0x9b, 0x8d, 0x2d, 0xf4, 0xb1, 0x85, 0x47, 0xdd, 0xdf,
	0x4c, 0x1b, 0x74, 0xfe, 0x0a, 0x80, 0x3c, 0x84, 0x81, 0x59, 0xab, 0xe4, 0x01, 0x26, 0xaf, 0x8a,
	0xe9, 0xc1, 0xd9, 0x3c, 0x70, 0xcf, 0xe7, 0x81, 0xfb, 0x77, 0x1e, 0xb8, 0x3f, 0x17, 0x81, 0x73,
	0xbe, 0x08, 0x9c, 0xdf, 0x8b, 0xc0, 0xf9, 0x1c, 0xe7, 0x85, 0x38, 0x39, 0x9d, 0xc4, 0xc7, 0x7c,
	0x9a, 0x58, 0x4d, 0x24, 0x07, 0xb2, 0x89, 0x8f, 0x9c, 0x67, 0xc9, 0x8f, 0x44, 0xbf, 0xde, 0x59,
	0xc5, 0x9a, 0x89, 0x87, 0xef, 0xf1, 0xd9, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xf2, 0xc4,
	0x68, 0x89, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApiariesCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ApiariesCount))
		i--
		dAtA[i] = 0x68
	}
	if len(m.ApiariesList) > 0 {
		for iNdEx := len(m.ApiariesList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApiariesList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x62
		}
	}
	if m.DecorationsCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.DecorationsCount))
		i--
		dAtA[i] = 0x58
	}
	if len(m.DecorationsList) > 0 {
		for iNdEx := len(m.DecorationsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DecorationsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if m.TreesCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TreesCount))
		i--
		dAtA[i] = 0x48
	}
	if len(m.TreesList) > 0 {
		for iNdEx := len(m.TreesList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TreesList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.FieldsCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.FieldsCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.FieldsList) > 0 {
		for iNdEx := len(m.FieldsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FieldsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AddressBearsList) > 0 {
		for iNdEx := len(m.AddressBearsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AddressBearsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.BearsCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.BearsCount))
		i--
		dAtA[i] = 0x20
	}
	if len(m.BearsList) > 0 {
		for iNdEx := len(m.BearsList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BearsList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.BearNamesList) > 0 {
		for iNdEx := len(m.BearNamesList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BearNamesList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.BearNamesList) > 0 {
		for _, e := range m.BearNamesList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BearsList) > 0 {
		for _, e := range m.BearsList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.BearsCount != 0 {
		n += 1 + sovGenesis(uint64(m.BearsCount))
	}
	if len(m.AddressBearsList) > 0 {
		for _, e := range m.AddressBearsList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FieldsList) > 0 {
		for _, e := range m.FieldsList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.FieldsCount != 0 {
		n += 1 + sovGenesis(uint64(m.FieldsCount))
	}
	if len(m.TreesList) > 0 {
		for _, e := range m.TreesList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.TreesCount != 0 {
		n += 1 + sovGenesis(uint64(m.TreesCount))
	}
	if len(m.DecorationsList) > 0 {
		for _, e := range m.DecorationsList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.DecorationsCount != 0 {
		n += 1 + sovGenesis(uint64(m.DecorationsCount))
	}
	if len(m.ApiariesList) > 0 {
		for _, e := range m.ApiariesList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.ApiariesCount != 0 {
		n += 1 + sovGenesis(uint64(m.ApiariesCount))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BearNamesList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BearNamesList = append(m.BearNamesList, BearNames{})
			if err := m.BearNamesList[len(m.BearNamesList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BearsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BearsList = append(m.BearsList, Bears{})
			if err := m.BearsList[len(m.BearsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BearsCount", wireType)
			}
			m.BearsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BearsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AddressBearsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AddressBearsList = append(m.AddressBearsList, AddressBears{})
			if err := m.AddressBearsList[len(m.AddressBearsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FieldsList = append(m.FieldsList, Fields{})
			if err := m.FieldsList[len(m.FieldsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FieldsCount", wireType)
			}
			m.FieldsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FieldsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreesList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreesList = append(m.TreesList, Trees{})
			if err := m.TreesList[len(m.TreesList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreesCount", wireType)
			}
			m.TreesCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TreesCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecorationsList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DecorationsList = append(m.DecorationsList, Decorations{})
			if err := m.DecorationsList[len(m.DecorationsList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecorationsCount", wireType)
			}
			m.DecorationsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DecorationsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiariesList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiariesList = append(m.ApiariesList, Apiaries{})
			if err := m.ApiariesList[len(m.ApiariesList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiariesCount", wireType)
			}
			m.ApiariesCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApiariesCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
