// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bears/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	BlocksPerHour    uint64                                   `protobuf:"varint,1,opt,name=blocks_per_hour,json=blocksPerHour,proto3" json:"blocks_per_hour,omitempty" yaml:"blocks_per_hour"`
	AirHistoryLength uint64                                   `protobuf:"varint,2,opt,name=air_history_length,json=airHistoryLength,proto3" json:"air_history_length,omitempty" yaml:"air_history_length"`
	BurnRate         github_com_cosmos_cosmos_sdk_types.Dec   `protobuf:"bytes,3,opt,name=burn_rate,json=burnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"burn_rate" yaml:"burn_rate"`
	PriceSetName     github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=price_set_name,json=priceSetName,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"price_set_name" yaml:"price_set_name"`
	PriceTile        github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=price_tile,json=priceTile,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"price_tile" yaml:"price_tile"`
	TreeTypes        []TreeParams                             `protobuf:"bytes,6,rep,name=tree_types,json=treeTypes,proto3" json:"tree_types" yaml:"tree_types"`
	DecorationTypes  []DecorationParams                       `protobuf:"bytes,7,rep,name=decoration_types,json=decorationTypes,proto3" json:"decoration_types" yaml:"decoration_types"`
	ApiaryTypes      []ApiaryParams                           `protobuf:"bytes,8,rep,name=apiary_types,json=apiaryTypes,proto3" json:"apiary_types" yaml:"apiary_types"`
	BeeTypes         []BeeParams                              `protobuf:"bytes,9,rep,name=bee_types,json=beeTypes,proto3" json:"bee_types" yaml:"bee_types"`
	HoneyDenom       string                                   `protobuf:"bytes,10,opt,name=honey_denom,json=honeyDenom,proto3" json:"honey_denom,omitempty" yaml:"honey_denom"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ad25feeeed35bd0, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBlocksPerHour() uint64 {
	if m != nil {
		return m.BlocksPerHour
	}
	return 0
}

func (m *Params) GetAirHistoryLength() uint64 {
	if m != nil {
		return m.AirHistoryLength
	}
	return 0
}

func (m *Params) GetPriceSetName() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.PriceSetName
	}
	return nil
}

func (m *Params) GetPriceTile() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.PriceTile
	}
	return nil
}

func (m *Params) GetTreeTypes() []TreeParams {
	if m != nil {
		return m.TreeTypes
	}
	return nil
}

func (m *Params) GetDecorationTypes() []DecorationParams {
	if m != nil {
		return m.DecorationTypes
	}
	return nil
}

func (m *Params) GetApiaryTypes() []ApiaryParams {
	if m != nil {
		return m.ApiaryTypes
	}
	return nil
}

func (m *Params) GetBeeTypes() []BeeParams {
	if m != nil {
		return m.BeeTypes
	}
	return nil
}

func (m *Params) GetHoneyDenom() string {
	if m != nil {
		return m.HoneyDenom
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "MonetaToday.honeywood.bears.Params")
}

func init() { proto.RegisterFile("bears/params.proto", fileDescriptor_8ad25feeeed35bd0) }

var fileDescriptor_8ad25feeeed35bd0 = []byte{
	// 636 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xcb, 0x6e, 0xd3, 0x4c,
	0x14, 0xc7, 0xe3, 0xaf, 0xfd, 0xda, 0x66, 0x5a, 0x68, 0x6a, 0x4a, 0xeb, 0xa6, 0xc2, 0xae, 0xbc,
	0x28, 0x61, 0x51, 0x5b, 0x85, 0x05, 0x52, 0x77, 0x98, 0x22, 0x05, 0x71, 0x51, 0x65, 0x22, 0x21,
	0x21, 0x21, 0x6b, 0xec, 0x1c, 0x25, 0xa3, 0xc6, 0x9e, 0x68, 0x3c, 0x01, 0xbc, 0x62, 0xcf, 0x8a,
	0x25, 0x4b, 0xd6, 0x3c, 0x49, 0x97, 0x5d, 0x22, 0x16, 0x06, 0x35, 0x0f, 0x80, 0x94, 0x27, 0x40,
	0x73, 0xc9, 0xa5, 0x45, 0x0a, 0xb0, 0xf2, 0xcc, 0xb9, 0xfc, 0x7f, 0x7f, 0x1d, 0x1f, 0x1b, 0x99,
	0x31, 0x60, 0x96, 0xfb, 0x7d, 0xcc, 0x70, 0x9a, 0x7b, 0x7d, 0x46, 0x39, 0x35, 0x77, 0x9f, 0xd1,
	0x0c, 0x38, 0x6e, 0xd1, 0x36, 0x2e, 0xbc, 0x2e, 0xcd, 0xa0, 0x78, 0x4b, 0x69, 0xdb, 0x93, 0x95,
	0xf5, 0xcd, 0x0e, 0xed, 0x50, 0x59, 0xe7, 0x8b, 0x93, 0x6a, 0xa9, 0xdb, 0x09, 0xcd, 0x53, 0x9a,
	0xfb, 0x31, 0xce, 0xc1, 0x7f, 0x73, 0x18, 0x03, 0xc7, 0x87, 0x7e, 0x42, 0x49, 0xa6, 0xf3, 0x9b,
	0x0a, 0x83, 0xfb, 0x04, 0x33, 0x02, 0x1a, 0x54, 0xdf, 0x56, 0xd1, 0x36, 0x24, 0x94, 0x61, 0x4e,
	0x68, 0x36, 0x4e, 0xd4, 0x54, 0x22, 0x86, 0x49, 0xe9, 0x86, 0x8a, 0x70, 0x36, 0x09, 0xb9, 0x3f,
	0x97, 0xd1, 0xd2, 0x89, 0xf4, 0x6d, 0x06, 0x68, 0x3d, 0xee, 0xd1, 0xe4, 0x34, 0x8f, 0xfa, 0xc0,
	0xa2, 0x2e, 0x1d, 0x30, 0xcb, 0xd8, 0x33, 0x1a, 0x8b, 0x41, 0x7d, 0x54, 0x3a, 0x5b, 0x05, 0x4e,
	0x7b, 0x47, 0xee, 0x95, 0x02, 0x37, 0xbc, 0xa6, 0x22, 0x27, 0xc0, 0x9a, 0x74, 0xc0, 0xcc, 0x27,
	0xc8, 0xc4, 0x84, 0x45, 0x5d, 0x92, 0x73, 0xca, 0x8a, 0xa8, 0x07, 0x59, 0x87, 0x77, 0xad, 0xff,
	0xa4, 0xcc, 0xad, 0x51, 0xe9, 0xec, 0x28, 0x99, 0xdf, 0x6b, 0xdc, 0xb0, 0x86, 0x09, 0x6b, 0xaa,
	0xd8, 0x53, 0x19, 0x32, 0x23, 0x54, 0x8d, 0x07, 0x2c, 0x8b, 0x18, 0xe6, 0x60, 0x2d, 0xec, 0x19,
	0x8d, 0x6a, 0x10, 0x9c, 0x95, 0x4e, 0xe5, 0x5b, 0xe9, 0xec, 0x77, 0x08, 0xef, 0x0e, 0x62, 0x2f,
	0xa1, 0xa9, 0xaf, 0xa7, 0xa6, 0x1e, 0x07, 0x79, 0xfb, 0xd4, 0xe7, 0x45, 0x1f, 0x72, 0xef, 0x18,
	0x92, 0x51, 0xe9, 0xd4, 0xb4, 0xf1, 0xb1, 0x90, 0x1b, 0xae, 0x88, 0x73, 0x88, 0x39, 0x98, 0x1f,
	0x0c, 0x74, 0xbd, 0xcf, 0x48, 0x02, 0x51, 0x0e, 0x3c, 0xca, 0x70, 0x0a, 0xd6, 0xe2, 0xde, 0x42,
	0x63, 0xf5, 0xee, 0x8e, 0xa7, 0xd4, 0x3c, 0xf1, 0x2a, 0x3c, 0xfd, 0x2a, 0xbc, 0x87, 0x94, 0x64,
	0xc1, 0x63, 0xe1, 0x60, 0x54, 0x3a, 0x37, 0x95, 0xee, 0xe5, 0x76, 0xf7, 0xcb, 0x77, 0xa7, 0xf1,
	0x17, 0xd6, 0x84, 0x52, 0x1e, 0xae, 0xc9, 0xe6, 0x17, 0xc0, 0x9f, 0xe3, 0x14, 0xcc, 0xf7, 0x08,
	0x29, 0x31, 0x4e, 0x7a, 0x60, 0xfd, 0xff, 0x27, 0x1f, 0x8f, 0xb4, 0x8f, 0x8d, 0x59, 0x1f, 0xa2,
	0xf5, 0xdf, 0x3c, 0x54, 0x65, 0x63, 0x8b, 0xf4, 0xc0, 0xc4, 0x08, 0x89, 0xcd, 0x88, 0x64, 0xda,
	0x5a, 0x92, 0x06, 0x6e, 0x7b, 0x73, 0xd6, 0xd8, 0x6b, 0x31, 0x00, 0xb5, 0x3c, 0xc1, 0xce, 0x65,
	0x3b, 0x53, 0x21, 0x37, 0xac, 0x8a, 0x4b, 0x4b, 0x9c, 0xcd, 0x02, 0xd5, 0xa6, 0x7b, 0xaa, 0x41,
	0xcb, 0x12, 0x74, 0x30, 0x17, 0x74, 0x3c, 0x69, 0xd2, 0x38, 0x47, 0xe3, 0xb6, 0x15, 0xee, 0xaa,
	0xa8, 0x1b, 0xae, 0x4f, 0x43, 0x0a, 0x4d, 0xd0, 0x9a, 0xfc, 0x70, 0x0a, 0x8d, 0x5d, 0x91, 0xd8,
	0x3b, 0x73, 0xb1, 0x0f, 0x64, 0x83, 0x46, 0xee, 0x6a, 0xe4, 0x0d, 0xbd, 0xc2, 0x33, 0x62, 0x6e,
	0xb8, 0xaa, 0xae, 0x0a, 0xf5, 0x1a, 0x55, 0xe3, 0xc9, 0x1c, 0xab, 0x92, 0xb3, 0x3f, 0x97, 0x13,
	0x4c, 0xc6, 0x68, 0x69, 0xc8, 0x78, 0x6b, 0xa7, 0x53, 0x5c, 0x89, 0xc7, 0x43, 0xbc, 0x8f, 0x56,
	0xa5, 0x40, 0xd4, 0x86, 0x8c, 0xa6, 0x16, 0x92, 0x1f, 0xc6, 0xd6, 0xa8, 0x74, 0x4c, 0xd5, 0x34,
	0x93, 0x74, 0x43, 0x24, 0x6f, 0xc7, 0xe2, 0x72, 0xb4, 0xf8, 0xe9, 0xb3, 0x53, 0x09, 0x9a, 0x67,
	0x17, 0xb6, 0x71, 0x7e, 0x61, 0x1b, 0x3f, 0x2e, 0x6c, 0xe3, 0xe3, 0xd0, 0xae, 0x9c, 0x0f, 0xed,
	0xca, 0xd7, 0xa1, 0x5d, 0x79, 0xe5, 0xcd, 0x6c, 0xcd, 0x8c, 0x5d, 0xbf, 0x29, 0x24, 0x5e, 0x52,
	0xda, 0xf6, 0xdf, 0xf9, 0xfa, 0x0f, 0x22, 0x8c, 0xc4, 0x4b, 0xf2, 0x17, 0x72, 0xef, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x84, 0x61, 0x9c, 0xa1, 0xff, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.HoneyDenom) > 0 {
		i -= len(m.HoneyDenom)
		copy(dAtA[i:], m.HoneyDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.HoneyDenom)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.BeeTypes) > 0 {
		for iNdEx := len(m.BeeTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BeeTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.ApiaryTypes) > 0 {
		for iNdEx := len(m.ApiaryTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ApiaryTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.DecorationTypes) > 0 {
		for iNdEx := len(m.DecorationTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DecorationTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.TreeTypes) > 0 {
		for iNdEx := len(m.TreeTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TreeTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.PriceTile) > 0 {
		for iNdEx := len(m.PriceTile) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PriceTile[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.PriceSetName) > 0 {
		for iNdEx := len(m.PriceSetName) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PriceSetName[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.BurnRate.Size()
		i -= size
		if _, err := m.BurnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.AirHistoryLength != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AirHistoryLength))
		i--
		dAtA[i] = 0x10
	}
	if m.BlocksPerHour != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BlocksPerHour))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlocksPerHour != 0 {
		n += 1 + sovParams(uint64(m.BlocksPerHour))
	}
	if m.AirHistoryLength != 0 {
		n += 1 + sovParams(uint64(m.AirHistoryLength))
	}
	l = m.BurnRate.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.PriceSetName) > 0 {
		for _, e := range m.PriceSetName {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.PriceTile) > 0 {
		for _, e := range m.PriceTile {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.TreeTypes) > 0 {
		for _, e := range m.TreeTypes {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.DecorationTypes) > 0 {
		for _, e := range m.DecorationTypes {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.ApiaryTypes) > 0 {
		for _, e := range m.ApiaryTypes {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	if len(m.BeeTypes) > 0 {
		for _, e := range m.BeeTypes {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.HoneyDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlocksPerHour", wireType)
			}
			m.BlocksPerHour = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlocksPerHour |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AirHistoryLength", wireType)
			}
			m.AirHistoryLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AirHistoryLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BurnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BurnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceSetName", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceSetName = append(m.PriceSetName, types.Coin{})
			if err := m.PriceSetName[len(m.PriceSetName)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceTile", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceTile = append(m.PriceTile, types.Coin{})
			if err := m.PriceTile[len(m.PriceTile)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TreeTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TreeTypes = append(m.TreeTypes, TreeParams{})
			if err := m.TreeTypes[len(m.TreeTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DecorationTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DecorationTypes = append(m.DecorationTypes, DecorationParams{})
			if err := m.DecorationTypes[len(m.DecorationTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApiaryTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ApiaryTypes = append(m.ApiaryTypes, ApiaryParams{})
			if err := m.ApiaryTypes[len(m.ApiaryTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeeTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeeTypes = append(m.BeeTypes, BeeParams{})
			if err := m.BeeTypes[len(m.BeeTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HoneyDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.HoneyDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
