// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: bears/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgInitGameAndSetName struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgInitGameAndSetName) Reset()         { *m = MsgInitGameAndSetName{} }
func (m *MsgInitGameAndSetName) String() string { return proto.CompactTextString(m) }
func (*MsgInitGameAndSetName) ProtoMessage()    {}
func (*MsgInitGameAndSetName) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{0}
}
func (m *MsgInitGameAndSetName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitGameAndSetName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitGameAndSetName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitGameAndSetName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitGameAndSetName.Merge(m, src)
}
func (m *MsgInitGameAndSetName) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitGameAndSetName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitGameAndSetName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitGameAndSetName proto.InternalMessageInfo

func (m *MsgInitGameAndSetName) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgInitGameAndSetName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgInitGameAndSetNameResponse struct {
}

func (m *MsgInitGameAndSetNameResponse) Reset()         { *m = MsgInitGameAndSetNameResponse{} }
func (m *MsgInitGameAndSetNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitGameAndSetNameResponse) ProtoMessage()    {}
func (*MsgInitGameAndSetNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{1}
}
func (m *MsgInitGameAndSetNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitGameAndSetNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitGameAndSetNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitGameAndSetNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitGameAndSetNameResponse.Merge(m, src)
}
func (m *MsgInitGameAndSetNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitGameAndSetNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitGameAndSetNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitGameAndSetNameResponse proto.InternalMessageInfo

type MsgSetName struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	BearId  uint64 `protobuf:"varint,2,opt,name=bearId,proto3" json:"bearId,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgSetName) Reset()         { *m = MsgSetName{} }
func (m *MsgSetName) String() string { return proto.CompactTextString(m) }
func (*MsgSetName) ProtoMessage()    {}
func (*MsgSetName) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{2}
}
func (m *MsgSetName) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetName.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetName.Merge(m, src)
}
func (m *MsgSetName) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetName) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetName.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetName proto.InternalMessageInfo

func (m *MsgSetName) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetName) GetBearId() uint64 {
	if m != nil {
		return m.BearId
	}
	return 0
}

func (m *MsgSetName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgSetNameResponse struct {
}

func (m *MsgSetNameResponse) Reset()         { *m = MsgSetNameResponse{} }
func (m *MsgSetNameResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetNameResponse) ProtoMessage()    {}
func (*MsgSetNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{3}
}
func (m *MsgSetNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetNameResponse.Merge(m, src)
}
func (m *MsgSetNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetNameResponse proto.InternalMessageInfo

type MsgInitGameAndExtendPlace struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgInitGameAndExtendPlace) Reset()         { *m = MsgInitGameAndExtendPlace{} }
func (m *MsgInitGameAndExtendPlace) String() string { return proto.CompactTextString(m) }
func (*MsgInitGameAndExtendPlace) ProtoMessage()    {}
func (*MsgInitGameAndExtendPlace) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{4}
}
func (m *MsgInitGameAndExtendPlace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitGameAndExtendPlace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitGameAndExtendPlace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitGameAndExtendPlace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitGameAndExtendPlace.Merge(m, src)
}
func (m *MsgInitGameAndExtendPlace) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitGameAndExtendPlace) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitGameAndExtendPlace.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitGameAndExtendPlace proto.InternalMessageInfo

func (m *MsgInitGameAndExtendPlace) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgInitGameAndExtendPlaceResponse struct {
	CountGrounds uint64 `protobuf:"varint,1,opt,name=countGrounds,proto3" json:"countGrounds,omitempty"`
}

func (m *MsgInitGameAndExtendPlaceResponse) Reset()         { *m = MsgInitGameAndExtendPlaceResponse{} }
func (m *MsgInitGameAndExtendPlaceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitGameAndExtendPlaceResponse) ProtoMessage()    {}
func (*MsgInitGameAndExtendPlaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{5}
}
func (m *MsgInitGameAndExtendPlaceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitGameAndExtendPlaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitGameAndExtendPlaceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitGameAndExtendPlaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitGameAndExtendPlaceResponse.Merge(m, src)
}
func (m *MsgInitGameAndExtendPlaceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitGameAndExtendPlaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitGameAndExtendPlaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitGameAndExtendPlaceResponse proto.InternalMessageInfo

func (m *MsgInitGameAndExtendPlaceResponse) GetCountGrounds() uint64 {
	if m != nil {
		return m.CountGrounds
	}
	return 0
}

type MsgExtendPlace struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgExtendPlace) Reset()         { *m = MsgExtendPlace{} }
func (m *MsgExtendPlace) String() string { return proto.CompactTextString(m) }
func (*MsgExtendPlace) ProtoMessage()    {}
func (*MsgExtendPlace) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{6}
}
func (m *MsgExtendPlace) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExtendPlace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExtendPlace.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExtendPlace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExtendPlace.Merge(m, src)
}
func (m *MsgExtendPlace) XXX_Size() int {
	return m.Size()
}
func (m *MsgExtendPlace) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExtendPlace.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExtendPlace proto.InternalMessageInfo

func (m *MsgExtendPlace) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgExtendPlace) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgExtendPlaceResponse struct {
	CountGrounds uint64 `protobuf:"varint,1,opt,name=countGrounds,proto3" json:"countGrounds,omitempty"`
}

func (m *MsgExtendPlaceResponse) Reset()         { *m = MsgExtendPlaceResponse{} }
func (m *MsgExtendPlaceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgExtendPlaceResponse) ProtoMessage()    {}
func (*MsgExtendPlaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{7}
}
func (m *MsgExtendPlaceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgExtendPlaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgExtendPlaceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgExtendPlaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgExtendPlaceResponse.Merge(m, src)
}
func (m *MsgExtendPlaceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgExtendPlaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgExtendPlaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgExtendPlaceResponse proto.InternalMessageInfo

func (m *MsgExtendPlaceResponse) GetCountGrounds() uint64 {
	if m != nil {
		return m.CountGrounds
	}
	return 0
}

type MsgInitGameAndCreateTree struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *MsgInitGameAndCreateTree) Reset()         { *m = MsgInitGameAndCreateTree{} }
func (m *MsgInitGameAndCreateTree) String() string { return proto.CompactTextString(m) }
func (*MsgInitGameAndCreateTree) ProtoMessage()    {}
func (*MsgInitGameAndCreateTree) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{8}
}
func (m *MsgInitGameAndCreateTree) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitGameAndCreateTree) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitGameAndCreateTree.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitGameAndCreateTree) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitGameAndCreateTree.Merge(m, src)
}
func (m *MsgInitGameAndCreateTree) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitGameAndCreateTree) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitGameAndCreateTree.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitGameAndCreateTree proto.InternalMessageInfo

func (m *MsgInitGameAndCreateTree) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

type MsgInitGameAndCreateTreeResponse struct {
	Tree *Trees `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
}

func (m *MsgInitGameAndCreateTreeResponse) Reset()         { *m = MsgInitGameAndCreateTreeResponse{} }
func (m *MsgInitGameAndCreateTreeResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitGameAndCreateTreeResponse) ProtoMessage()    {}
func (*MsgInitGameAndCreateTreeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b4b1de47af2539c, []int{9}
}
func (m *MsgInitGameAndCreateTreeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitGameAndCreateTreeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitGameAndCreateTreeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitGameAndCreateTreeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitGameAndCreateTreeResponse.Merge(m, src)
}
func (m *MsgInitGameAndCreateTreeResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitGameAndCreateTreeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitGameAndCreateTreeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitGameAndCreateTreeResponse proto.InternalMessageInfo

func (m *MsgInitGameAndCreateTreeResponse) GetTree() *Trees {
	if m != nil {
		return m.Tree
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgInitGameAndSetName)(nil), "MonetaToday.honeywood.bears.MsgInitGameAndSetName")
	proto.RegisterType((*MsgInitGameAndSetNameResponse)(nil), "MonetaToday.honeywood.bears.MsgInitGameAndSetNameResponse")
	proto.RegisterType((*MsgSetName)(nil), "MonetaToday.honeywood.bears.MsgSetName")
	proto.RegisterType((*MsgSetNameResponse)(nil), "MonetaToday.honeywood.bears.MsgSetNameResponse")
	proto.RegisterType((*MsgInitGameAndExtendPlace)(nil), "MonetaToday.honeywood.bears.MsgInitGameAndExtendPlace")
	proto.RegisterType((*MsgInitGameAndExtendPlaceResponse)(nil), "MonetaToday.honeywood.bears.MsgInitGameAndExtendPlaceResponse")
	proto.RegisterType((*MsgExtendPlace)(nil), "MonetaToday.honeywood.bears.MsgExtendPlace")
	proto.RegisterType((*MsgExtendPlaceResponse)(nil), "MonetaToday.honeywood.bears.MsgExtendPlaceResponse")
	proto.RegisterType((*MsgInitGameAndCreateTree)(nil), "MonetaToday.honeywood.bears.MsgInitGameAndCreateTree")
	proto.RegisterType((*MsgInitGameAndCreateTreeResponse)(nil), "MonetaToday.honeywood.bears.MsgInitGameAndCreateTreeResponse")
}

func init() { proto.RegisterFile("bears/tx.proto", fileDescriptor_0b4b1de47af2539c) }

var fileDescriptor_0b4b1de47af2539c = []byte{
	// 456 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xc1, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0x33, 0x69, 0x6c, 0xf1, 0x55, 0x02, 0x0e, 0x36, 0xc4, 0x88, 0x6b, 0x9d, 0x8b, 0x82,
	0xb0, 0x0b, 0xa9, 0xed, 0xa1, 0xa8, 0xa0, 0x52, 0xd2, 0x1e, 0x56, 0x64, 0x2d, 0x08, 0xbd, 0x4d,
	0x76, 0x1e, 0xdb, 0x80, 0x99, 0x09, 0x3b, 0x13, 0x4c, 0xee, 0x7a, 0x14, 0xfa, 0x67, 0x79, 0xec,
	0xd1, 0xa3, 0x24, 0xff, 0x88, 0xec, 0x98, 0xdd, 0xee, 0xc2, 0x66, 0xd3, 0xed, 0x6d, 0x66, 0x78,
	0xdf, 0xf7, 0xfb, 0x1e, 0x7c, 0x0c, 0xb4, 0x87, 0xc8, 0x63, 0xed, 0x99, 0x99, 0x3b, 0x89, 0x95,
	0x51, 0xf4, 0x89, 0xaf, 0x24, 0x1a, 0x7e, 0xae, 0x04, 0x9f, 0xbb, 0x97, 0x4a, 0xe2, 0xfc, 0xbb,
	0x52, 0xc2, 0xb5, 0x53, 0xbd, 0x87, 0xab, 0xe1, 0x18, 0x51, 0xff, 0x9f, 0x67, 0x27, 0xb0, 0xe7,
	0xeb, 0xe8, 0x4c, 0x8e, 0xcc, 0x80, 0x8f, 0xf1, 0xbd, 0x14, 0x5f, 0xd0, 0x7c, 0xe2, 0x63, 0xa4,
	0x5d, 0xd8, 0x09, 0x63, 0xe4, 0x46, 0xc5, 0x5d, 0xb2, 0x4f, 0x5e, 0xde, 0x0f, 0xd2, 0x2b, 0xa5,
	0xd0, 0x92, 0x7c, 0x8c, 0xdd, 0xa6, 0x7d, 0xb6, 0x67, 0xf6, 0x0c, 0x9e, 0x96, 0xda, 0x04, 0xa8,
	0x27, 0x4a, 0x6a, 0x64, 0x01, 0x80, 0xaf, 0xa3, 0xcd, 0xe6, 0x1d, 0xd8, 0x4e, 0x42, 0x9e, 0x09,
	0x6b, 0xdf, 0x0a, 0x56, 0xb7, 0x0c, 0xba, 0x95, 0x83, 0x3e, 0x02, 0x7a, 0xe3, 0x99, 0x91, 0x0e,
	0xe1, 0x71, 0x31, 0xca, 0xc9, 0xcc, 0xa0, 0x14, 0x9f, 0xbf, 0xf1, 0xb0, 0x02, 0xcc, 0x06, 0xf0,
	0x7c, 0xad, 0x2c, 0xf5, 0xa6, 0x0c, 0x1e, 0x84, 0x6a, 0x2a, 0xcd, 0x20, 0x56, 0x53, 0x29, 0xb4,
	0xf5, 0x68, 0x05, 0x85, 0x37, 0x76, 0x0c, 0x6d, 0x5f, 0x47, 0xb7, 0x82, 0xd2, 0x36, 0x34, 0x47,
	0xe9, 0xa6, 0xcd, 0x91, 0x60, 0x6f, 0xa0, 0x53, 0xd4, 0xd6, 0x22, 0xbf, 0x86, 0x6e, 0x71, 0x85,
	0x8f, 0x09, 0x06, 0xcf, 0x63, 0xac, 0x5a, 0xfc, 0x02, 0xf6, 0xd7, 0xa9, 0x32, 0xfa, 0x11, 0xb4,
	0x92, 0xd2, 0x58, 0xe9, 0x6e, 0x9f, 0xb9, 0x15, 0x25, 0x73, 0x13, 0xa1, 0x0e, 0xec, 0x7c, 0xff,
	0xe7, 0x3d, 0xd8, 0xf2, 0x75, 0x44, 0x7f, 0x10, 0xa0, 0x25, 0x1d, 0xeb, 0x57, 0x1a, 0x95, 0x16,
	0xaa, 0x77, 0x5c, 0x5f, 0x93, 0xad, 0x11, 0xc2, 0x4e, 0x8a, 0x7e, 0xb1, 0xc9, 0x26, 0xe5, 0x79,
	0xb7, 0x1c, 0xcc, 0x20, 0x57, 0x04, 0x3a, 0x6b, 0xda, 0x77, 0x54, 0x23, 0x7b, 0x4e, 0xd7, 0x7b,
	0x77, 0x37, 0x5d, 0x16, 0x49, 0xc1, 0x6e, 0x3e, 0xc6, 0xab, 0x4d, 0x76, 0x79, 0xf6, 0x41, 0x8d,
	0xe1, 0x0c, 0xf8, 0x8b, 0xc0, 0x5e, 0x79, 0x0f, 0x0f, 0x6b, 0xac, 0x72, 0x23, 0xeb, 0xbd, 0xbd,
	0x93, 0x2c, 0xcd, 0xf3, 0xe1, 0xf4, 0xf7, 0xc2, 0x21, 0xd7, 0x0b, 0x87, 0xfc, 0x5d, 0x38, 0xe4,
	0x6a, 0xe9, 0x34, 0xae, 0x97, 0x4e, 0xe3, 0xcf, 0xd2, 0x69, 0x5c, 0xb8, 0xd1, 0xc8, 0x5c, 0x4e,
	0x87, 0x6e, 0xa8, 0xc6, 0x5e, 0x0e, 0xe1, 0x9d, 0x26, 0x88, 0xaf, 0x4a, 0x09, 0x6f, 0xe6, 0xad,
	0x7e, 0xcd, 0xf9, 0x04, 0xf5, 0x70, 0xdb, 0x7e, 0x9b, 0x07, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x63, 0xb8, 0x7c, 0x82, 0x78, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	InitGameAndSetName(ctx context.Context, in *MsgInitGameAndSetName, opts ...grpc.CallOption) (*MsgInitGameAndSetNameResponse, error)
	SetName(ctx context.Context, in *MsgSetName, opts ...grpc.CallOption) (*MsgSetNameResponse, error)
	InitGameAndExtendPlace(ctx context.Context, in *MsgInitGameAndExtendPlace, opts ...grpc.CallOption) (*MsgInitGameAndExtendPlaceResponse, error)
	ExtendPlace(ctx context.Context, in *MsgExtendPlace, opts ...grpc.CallOption) (*MsgExtendPlaceResponse, error)
	InitGameAndCreateTree(ctx context.Context, in *MsgInitGameAndCreateTree, opts ...grpc.CallOption) (*MsgInitGameAndCreateTreeResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) InitGameAndSetName(ctx context.Context, in *MsgInitGameAndSetName, opts ...grpc.CallOption) (*MsgInitGameAndSetNameResponse, error) {
	out := new(MsgInitGameAndSetNameResponse)
	err := c.cc.Invoke(ctx, "/MonetaToday.honeywood.bears.Msg/InitGameAndSetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetName(ctx context.Context, in *MsgSetName, opts ...grpc.CallOption) (*MsgSetNameResponse, error) {
	out := new(MsgSetNameResponse)
	err := c.cc.Invoke(ctx, "/MonetaToday.honeywood.bears.Msg/SetName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitGameAndExtendPlace(ctx context.Context, in *MsgInitGameAndExtendPlace, opts ...grpc.CallOption) (*MsgInitGameAndExtendPlaceResponse, error) {
	out := new(MsgInitGameAndExtendPlaceResponse)
	err := c.cc.Invoke(ctx, "/MonetaToday.honeywood.bears.Msg/InitGameAndExtendPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ExtendPlace(ctx context.Context, in *MsgExtendPlace, opts ...grpc.CallOption) (*MsgExtendPlaceResponse, error) {
	out := new(MsgExtendPlaceResponse)
	err := c.cc.Invoke(ctx, "/MonetaToday.honeywood.bears.Msg/ExtendPlace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitGameAndCreateTree(ctx context.Context, in *MsgInitGameAndCreateTree, opts ...grpc.CallOption) (*MsgInitGameAndCreateTreeResponse, error) {
	out := new(MsgInitGameAndCreateTreeResponse)
	err := c.cc.Invoke(ctx, "/MonetaToday.honeywood.bears.Msg/InitGameAndCreateTree", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	InitGameAndSetName(context.Context, *MsgInitGameAndSetName) (*MsgInitGameAndSetNameResponse, error)
	SetName(context.Context, *MsgSetName) (*MsgSetNameResponse, error)
	InitGameAndExtendPlace(context.Context, *MsgInitGameAndExtendPlace) (*MsgInitGameAndExtendPlaceResponse, error)
	ExtendPlace(context.Context, *MsgExtendPlace) (*MsgExtendPlaceResponse, error)
	InitGameAndCreateTree(context.Context, *MsgInitGameAndCreateTree) (*MsgInitGameAndCreateTreeResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) InitGameAndSetName(ctx context.Context, req *MsgInitGameAndSetName) (*MsgInitGameAndSetNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitGameAndSetName not implemented")
}
func (*UnimplementedMsgServer) SetName(ctx context.Context, req *MsgSetName) (*MsgSetNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetName not implemented")
}
func (*UnimplementedMsgServer) InitGameAndExtendPlace(ctx context.Context, req *MsgInitGameAndExtendPlace) (*MsgInitGameAndExtendPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitGameAndExtendPlace not implemented")
}
func (*UnimplementedMsgServer) ExtendPlace(ctx context.Context, req *MsgExtendPlace) (*MsgExtendPlaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtendPlace not implemented")
}
func (*UnimplementedMsgServer) InitGameAndCreateTree(ctx context.Context, req *MsgInitGameAndCreateTree) (*MsgInitGameAndCreateTreeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitGameAndCreateTree not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_InitGameAndSetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitGameAndSetName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitGameAndSetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MonetaToday.honeywood.bears.Msg/InitGameAndSetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitGameAndSetName(ctx, req.(*MsgInitGameAndSetName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MonetaToday.honeywood.bears.Msg/SetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetName(ctx, req.(*MsgSetName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitGameAndExtendPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitGameAndExtendPlace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitGameAndExtendPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MonetaToday.honeywood.bears.Msg/InitGameAndExtendPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitGameAndExtendPlace(ctx, req.(*MsgInitGameAndExtendPlace))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ExtendPlace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgExtendPlace)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ExtendPlace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MonetaToday.honeywood.bears.Msg/ExtendPlace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ExtendPlace(ctx, req.(*MsgExtendPlace))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitGameAndCreateTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitGameAndCreateTree)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitGameAndCreateTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/MonetaToday.honeywood.bears.Msg/InitGameAndCreateTree",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitGameAndCreateTree(ctx, req.(*MsgInitGameAndCreateTree))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "MonetaToday.honeywood.bears.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitGameAndSetName",
			Handler:    _Msg_InitGameAndSetName_Handler,
		},
		{
			MethodName: "SetName",
			Handler:    _Msg_SetName_Handler,
		},
		{
			MethodName: "InitGameAndExtendPlace",
			Handler:    _Msg_InitGameAndExtendPlace_Handler,
		},
		{
			MethodName: "ExtendPlace",
			Handler:    _Msg_ExtendPlace_Handler,
		},
		{
			MethodName: "InitGameAndCreateTree",
			Handler:    _Msg_InitGameAndCreateTree_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bears/tx.proto",
}

func (m *MsgInitGameAndSetName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitGameAndSetName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitGameAndSetName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitGameAndSetNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitGameAndSetNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitGameAndSetNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetName) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetName) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetName) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BearId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BearId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInitGameAndExtendPlace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitGameAndExtendPlace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitGameAndExtendPlace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitGameAndExtendPlaceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitGameAndExtendPlaceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitGameAndExtendPlaceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CountGrounds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CountGrounds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgExtendPlace) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExtendPlace) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExtendPlace) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgExtendPlaceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgExtendPlaceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgExtendPlaceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CountGrounds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CountGrounds))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitGameAndCreateTree) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitGameAndCreateTree) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitGameAndCreateTree) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitGameAndCreateTreeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitGameAndCreateTreeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitGameAndCreateTreeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Tree != nil {
		{
			size, err := m.Tree.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgInitGameAndSetName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitGameAndSetNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetName) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BearId != 0 {
		n += 1 + sovTx(uint64(m.BearId))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInitGameAndExtendPlace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitGameAndExtendPlaceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CountGrounds != 0 {
		n += 1 + sovTx(uint64(m.CountGrounds))
	}
	return n
}

func (m *MsgExtendPlace) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgExtendPlaceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CountGrounds != 0 {
		n += 1 + sovTx(uint64(m.CountGrounds))
	}
	return n
}

func (m *MsgInitGameAndCreateTree) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgInitGameAndCreateTreeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Tree != nil {
		l = m.Tree.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgInitGameAndSetName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitGameAndSetName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitGameAndSetName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitGameAndSetNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitGameAndSetNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitGameAndSetNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetName) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetName: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetName: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BearId", wireType)
			}
			m.BearId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BearId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitGameAndExtendPlace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitGameAndExtendPlace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitGameAndExtendPlace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitGameAndExtendPlaceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitGameAndExtendPlaceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitGameAndExtendPlaceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountGrounds", wireType)
			}
			m.CountGrounds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountGrounds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExtendPlace) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExtendPlace: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExtendPlace: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgExtendPlaceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgExtendPlaceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgExtendPlaceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CountGrounds", wireType)
			}
			m.CountGrounds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CountGrounds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitGameAndCreateTree) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitGameAndCreateTree: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitGameAndCreateTree: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitGameAndCreateTreeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitGameAndCreateTreeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitGameAndCreateTreeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tree", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Tree == nil {
				m.Tree = &Trees{}
			}
			if err := m.Tree.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
