build:
  binary: "honeyd"
init:
  config:
    moniker: "cone-company-stake-1"
    consensus:
      timeout_commit: "5s"
  app:
    minimum-gas-prices: "0.05uhoney,0.000005cone"
accounts:
  - name: "honey-pre-private"
    address: "bears1w3txfx67gtuaz3xxf3ttqlxka7mfextzu2aje9"
    coins: ["15000000000000uhoney"]
  - name: "honey-team"
    address: "bears1sqvyny30arlm4538ayu4d8urw8yzhtjtpkql28"
    coins: ["15000000000000uhoney"]
  - name: "honey-advisory"
    address: "bears13tpvdg8xqx0q08lfnve6w8kqx3s4fpw074p4jt"
    coins: ["1800000000000uhoney"]
  - name: "honey-rewards"
    address: "bears1smpurvyfg008k606nfs5jr7024xf4zlvf0934f"
    coins: ["500000000000uhoney"]
  - name: "honey-marketing"
    address: "bears1yckxajewmy2yrzapr9yv5ey8txpxck6552n42d"
    coins: ["4000000000000uhoney"]
  - name: "honey-web-sale"
    address: "bears1ucqjfkcf8wer4lglsg062hpjmnupm9y68ylzgw"
    coins: ["25000000000000uhoney"]
  - name: "honey-igo"
    address: "bears1nc6hqyl8ujeqcefkndurjj3h7njf09jwwcx3a8"
    coins: ["41666667000000uhoney"]
  - name: "honey-liquidity"
    address: "bears1fqepqpwhsn0zlu5ydvzwkq6pszejcfsy92qw2y"
    coins: ["185000000000000uhoney"]

  - name: "cone-pre-private"
    address: "bears1n4hrlxmyc6nwzqh0f0hhq3ahlaga5h20wxphfv"
    coins: ["500000cone"]
  - name: "cone-private-1"
    address: "bears198zt7w2n5469ncmhzm3l67pahacyeg454a3h5u"
    coins: ["1923077cone"]
  - name: "cone-private-2"
    address: "bears1f0rmz8z22zmjpg4cysuky50mgaw6782dq7gz3d"
    coins: ["1470588cone"]
  - name: "cone-company-stake-1"
    coins: ["3400000cone"]
  - name: "cone-company-stake-2"
    address: "bears1ktszane2hq4rc3khgj9pkrxhszeetqpxf8my7a"
    coins: ["3400000cone"]
  - name: "cone-company-stake-3"
    address: "bears1k2hhnm4dj6klkcgglzmaqpqtypllg4rf3jy06a"
    coins: ["3400000cone"]
  - name: "cone-rewards"
    address: "bears1rvtvnk7pdtxwn5gteu6slxfylkyzxmfjg4elht"
    coins: ["900000cone"]
  - name: "cone-team"
    address: "bears1ww27cag59sunfuvqmntkk38n76a639r46gy70e"
    coins: ["1000000cone"]
  - name: "cone-advisory"
    address: "bears1ky92wllu6h7wgqtadem764kh40ynzwa0pndyx9"
    coins: ["200000cone"]
  - name: "cone-marketing"
    address: "bears15jnxsqty699ma05pxkhecvrpfux0aehcgxlxcq"
    coins: ["300000cone"]
  - name: "cone-liquidity"
    address: "bears1p5ym6hugkgvc9zvwd6hj36s5h7n7w92zthet5g"
    coins: ["2500000cone"]
validator:
  name: "cone-company-stake-1"
  staked: "3400000cone"
client:
  # openapi:
  #   path: "docs/static/openapi.yml"
  # vuex:
  #   path: "vue/src/store"
# faucet:
#   name: bob
#   coins: ["5uhoney", "100000stake"]
genesis:
  app_state:
    slashing:
      params:
        downtime_jail_duration: "3600s"
    bank:
      params:
        send_enabled:
          - denom: "uhoney"
            enabled: false
          - denom: "cone"
            enabled: false
        unlocked_senders:
          - address: "bears198zt7w2n5469ncmhzm3l67pahacyeg454a3h5u"
            denoms:
              - "cone"
          - address: "bears1n4hrlxmyc6nwzqh0f0hhq3ahlaga5h20wxphfv"
            denoms:
              - "cone"
          - address: "bears1f0rmz8z22zmjpg4cysuky50mgaw6782dq7gz3d"
            denoms:
              - "cone"
          - address: "bears1ww27cag59sunfuvqmntkk38n76a639r46gy70e"
            denoms:
              - "cone"
          - address: "bears1ky92wllu6h7wgqtadem764kh40ynzwa0pndyx9"
            denoms:
              - "cone"
          - address: "bears1fqepqpwhsn0zlu5ydvzwkq6pszejcfsy92qw2y"
            denoms:
              - "uhoney"
          - address: "bears1ucqjfkcf8wer4lglsg062hpjmnupm9y68ylzgw"
            denoms:
              - "uhoney"
        unlocked_receivers:
          - address: "bears17588vth3rrcamljd7hjkxp0jm5y7mvdf222lwy"
            denoms:
              - "uhoney"
      denom_metadata:
        - name: "HoneyCoin"
          description: "HoneyCoin is a native coin which is used to play"
          symbol: "HONEY"
          base: "uhoney"
          display: "honey"
          denom_units:
            - denom: "uhoney"
              exponent: 0
            - denom: "honey"
              exponent: 6
        - name: "CONE"
          description: "CONE is a native coin which is used to stake and governance"
          symbol: "CONE"
          base: "cone"
          display: "cone"
          denom_units:
            - denom: "cone"
              exponent: 0
    crisis:
      constant_fee:
        denom: "cone"
        amount: "1000"
    staking:
      params:
        bond_denom: "cone"
    distribution:
      params:
        community_tax: "0"
    mint:
      params:
        mint_denom: "uhoney"
        goal_bonded: "0.000000000000000001"
        inflation_max: "0.000000000000000001"
        inflation_min: "0.000000000000000001"
        inflation_rate_change: "0.000000000000000001"
    gov:
      deposit_params:
        min_deposit:
          - denom: "cone"
            amount: "10000"
        max_deposit_period: "172800s"
      voting_params:
        voting_period: "43200s"
    bears:
      airInfo:
        supply: "11000"
        consume: "10000"
      params:
        bear_air_consume: "1"
        air_history_length: "518400"
        blocks_per_hour: "720"
        burn_rate: "0.5"
        price_set_name: 
          - denom: "uhoney"
            amount: "100000000"

        field_types:
          - field_type: "DEFAULT"
            price_tile:
              - denom: "uhoney"
                amount: "100000000"

        tree_types:
          - tree_type: OAK
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: SPRUCE
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: APPLE_TREE
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: WILLOW
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          # - tree_type: BUSH
          #   air_supply: "1"
          #   price:
          #     - denom: "uhoney"
          #       amount: "200000000"

        decoration_types:
          - decoration_type: "FLOWERS"
            price:
              - denom: "uhoney"
                amount: "100000000"
          - decoration_type: "FLAG"
            price:
              - denom: "uhoney"
                amount: "150000000"
          - decoration_type: "LAMP"
            price:
              - denom: "uhoney"
                amount: "200000000"
          - decoration_type: "FLOWER_BARREL"
            price:
              - denom: "uhoney"
                amount: "220000000" 
          - decoration_type: "FOUNTAIN"
            price:
              - denom: "uhoney"
                amount: "300000000"
          - decoration_type: "FIRST_BEEHIVE"
            price:
              - denom: "uhoney"
                amount: "1000000000"
          - decoration_type: "BEE_THE_SAVIOR"
            price:
              - denom: "uhoney"
                amount: "500000000"
        
        apiary_types:
          - apiary_type: "BEE_HOUSE"
            space_available: 5
            max_honey: "10000000"
            price:
            - denom: "uhoney"
              amount: "500000000"
            deleteReward:
            - denom: "uhoney"
              amount: "250000000"
          - apiary_type: "APIARY"
            space_available: 8
            max_honey: "20000000"
            price:
            - denom: "uhoney"
              amount: "900000000"
            deleteReward:
            - denom: "uhoney"
              amount: "450000000"
          - apiary_type: "ALVEARY"
            space_available: 12
            max_honey: "35000000"
            price:
            - denom: "uhoney"
              amount: "1500000000"
            deleteReward:
            - denom: "uhoney"
              amount: "750000000"
          - apiary_type: "FOREST_BEEHIVE"
            space_available: 5
            max_honey: "30000000"
            price:
            - denom: "uhoney"
              amount: "1000000000"
            deleteReward:
            - denom: "uhoney"
              amount: "500000000"

        bee_types:
          - bee_type: "SMALL_BEE"
            honey_per_block: "792"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1100000000"
          - bee_type: "BEE"
            honey_per_block: "875"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1200000000"
          - bee_type: "LUCKY_BEE"
            honey_per_block: "944"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1280000000"
          - bee_type: "HONEY_BEE"
            honey_per_block: "1028"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1370000000"
          - bee_type: "SKILLED_BEE"
            honey_per_block: "1139"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1500000000"
          - bee_type: "CURIOUS_BEE"
            honey_per_block: "1264"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1650000000"
          - bee_type: "HONEY_EXPLORER"
            honey_per_block: "1375"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1780000000"
          - bee_type: "HONEY_HUNTER"
            honey_per_block: "1486"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1800000000"
          - bee_type: "WONDER_BEE"
            honey_per_block: "1667"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "2100000000"
          - bee_type: "DIAMOND_STING"
            honey_per_block: "1917"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "2350000000"
          - bee_type: "FOREST_BEE"
            honey_per_block: "847"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1150000000"
          - bee_type: "FOREST_EXPLORER"
            honey_per_block: "1389"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1780000000"
          - bee_type: "FOREST_ACE"
            honey_per_block: "1986"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "2400000000"