build:
  binary: "honeyd"
init:
  config:
    consensus:
      timeout_commit: "5s"
  app:
    minimum-gas-prices: "5uhoney"
accounts:
  - name: alice
    coins: ["200000000cone"]
  - name: bob
    coins: ["100000000000000000000000000000000000000000000000uhoney"]
  - name: koss
    coins: ["10000000000000000000000000000000000000uhoney", "100000000000cone"]
  - name: oleg
    coins: ["10000000000000000000000000000000000000uhoney", "100000000000cone"]
  - name: test
    coins: ["0uhoney", "0cone"]
validator:
  name: alice
  staked: "100000000cone"
client:
  # openapi:
  #   path: "docs/static/openapi.yml"
  # vuex:
  #   path: "vue/src/store"
# faucet:
#   name: bob
#   coins: ["5uhoney", "100000stake"]
genesis:
  app_state:
    bank:
      denom_metadata:
        - name: "HoneyCoin"
          description: "HoneyCoin is a native coin which is used to play"
          symbol: "HONEY"
          base: "uhoney"
          display: "honey"
          denom_units:
            - denom: "uhoney"
              exponent: 0
            - denom: "honey"
              exponent: 6
        - name: "CONE"
          description: "CONE is a native coin which is used to stake and governance"
          symbol: "CONE"
          base: "cone"
          display: "cone"
          denom_units:
            - denom: "cone"
              exponent: 0
    crisis:
      constant_fee:
        denom: "cone"
        amount: "1000"
    staking:
      params:
        bond_denom: "cone"
    distribution:
      params:
        community_tax: "0"
    mint:
      params:
        mint_denom: "uhoney"
        goal_bonded: "0.000000000000000001"
        inflation_max: "0.000000000000000001"
        inflation_min: "0.000000000000000001"
        inflation_rate_change: "0.000000000000000001"
    gov:
      deposit_params:
        min_deposit:
          - denom: "cone"
            amount: "10000"
        max_deposit_period: "172800s"
      voting_params:
        voting_period: "172800s"
    bears:
      airInfo:
        supply: "1"
        consume: "1"
        history: 
          - height: "0"
            count: "1"
            purity: "1"
      params:
        honey_denom: "uhoney"
        air_history_length: "518400"
        blocks_per_hour: "720"
        burn_rate: "0.5"
        price_set_name: 
          - denom: "uhoney"
            amount: "100000000"

        field_types:
          - field_type: "DEFAULT"
            price_tile:
              - denom: "uhoney"
                amount: "100000000"

        tree_types:
          - tree_type: OAK
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: SPRUCE
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: APPLE_TREE
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: WILLOW
            air_supply: "1"
            price:
              - denom: "uhoney"
                amount: "1500000000"
            reward:
              - denom: "cone"
                amount: "150"

        decoration_types:
          - decoration_type: "FLOWERS"
            price:
              - denom: "uhoney"
                amount: "100000000"
          - decoration_type: "FLAG"
            price:
              - denom: "uhoney"
                amount: "150000000"
          - decoration_type: "LAMP"
            price:
              - denom: "uhoney"
                amount: "200000000"
          - decoration_type: "FLOWER_BARREL"
            price:
              - denom: "uhoney"
                amount: "500000000" 
          - decoration_type: "FOUNTAIN"
            price:
              - denom: "uhoney"
                amount: "1000000000" 
        
        apiary_types:
          - apiary_type: "BEE_HOUSE"
            space_available: 5
            max_honey: "5000000"
            price:
            - denom: "uhoney"
              amount: "500000000"
            deleteReward:
            - denom: "uhoney"
              amount: "250000000"
          - apiary_type: "APIARY"
            space_available: 8
            max_honey: "15000000"
            price:
            - denom: "uhoney"
              amount: "900000000"
            deleteReward:
            - denom: "uhoney"
              amount: "450000000"
          - apiary_type: "ALVEARY"
            space_available: 12
            max_honey: "25000000"
            price:
            - denom: "uhoney"
              amount: "1500000000"
            deleteReward:
            - denom: "uhoney"
              amount: "750000000"

        bee_types:
          - bee_type: "SMALL_BEE"
            honey_per_hour: "550000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1100000000"
          - bee_type: "BEE"
            honey_per_hour: "620000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1200000000"
          - bee_type: "LUCKY_BEE"
            honey_per_hour: "640000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1280000000"
          - bee_type: "HONEY_BEE"
            honey_per_hour: "660000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1370000000"
          - bee_type: "SKILLED_BEE"
            honey_per_hour: "710000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1500000000"
          - bee_type: "CURIOUS_BEE"
            honey_per_hour: "750000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1650000000"
          - bee_type: "HONEY_EXPLORER"
            honey_per_hour: "800000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1780000000"
          - bee_type: "HONEY_HUNTER"
            honey_per_hour: "840000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "1800000000"
          - bee_type: "WONDER_BEE"
            honey_per_hour: "850000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "2100000000"
          - bee_type: "DIAMOND_STING"
            honey_per_hour: "900000"
            body_size: 1
            air_count_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "uhoney"
              amount: "2350000000"