init:
  app:
    minimum-gas-prices: "0.000005honey"
accounts:
  - name: alice
    coins: ["20000honey", "200000000cone"]
  - name: bob
    coins: ["10000honey", "100000000cone"]
  - name: bobi
    coins: ["100000honey", "100000000cone"]
validator:
  name: alice
  staked: "100000000cone"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5honey", "100000stake"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "cone"
    gov:
      deposit_params:
        min_deposit:
          - denom: "cone"
            amount: "10000"
        max_deposit_period: "172800s"
      voting_params:
        voting_period: "172800s"
    bears:
      params:
        set_name_price: 
          denom: "honey"
          amount: "100"
        one_ground_price: 
          denom: "honey"
          amount: "100"