build:
  binary: "honeyd"
init:
  config:
    consensus:
      timeout_commit: "5s"
  app:
    minimum-gas-prices: "0.000005honey"
accounts:
  - name: alice
    coins: ["20000honey", "200000000cone"]
  - name: bob
    coins: ["1000000000honey"]
  - name: bobi
    coins: ["100000honey"]
validator:
  name: alice
  staked: "100000000cone"
client:
  # openapi:
  #   path: "docs/static/openapi.yml"
  # vuex:
  #   path: "vue/src/store"
# faucet:
#   name: bob
#   coins: ["5honey", "100000stake"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "cone"
    gov:
      deposit_params:
        min_deposit:
          - denom: "cone"
            amount: "10000"
        max_deposit_period: "172800s"
      voting_params:
        voting_period: "172800s"
    bears:
      airInfo:
        supply: "1"
        consume: "1"
        history: 
          - height: "0"
            count: "1"
            purity: "1"
      params:
        honey_denom: "honey"
        air_history_length: "518400"
        blocks_per_hour: "720"
        burn_rate: "0.5"
        price_set_name: 
          - denom: "honey"
            amount: "100"

        field_types:
          - field_type: "DEFAULT"
            price_tile:
              - denom: "honey"
                amount: "100"

        tree_types:
          - tree_type: OAK
            air_supply: "1"
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: SPRUCE
            air_supply: "1"
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: APPLE_TREE
            air_supply: "1"
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: WILLOW
            air_supply: "1"
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"

        decoration_types:
          - decoration_type: "FLOWERS"
            price:
              - denom: "honey"
                amount: "100"
          - decoration_type: "FLAG"
            price:
              - denom: "honey"
                amount: "150"
          - decoration_type: "LAMP"
            price:
              - denom: "honey"
                amount: "200"
          - decoration_type: "GREEN_BEE"
            price:
              - denom: "honey"
                amount: "500" 
          - decoration_type: "FOUNTAIN"
            price:
              - denom: "honey"
                amount: "1000" 
        
        apiary_types:
          - apiary_type: "BEE_HOUSE"
            space_available: 5
            max_honey: "5"
            price:
            - denom: "honey"
              amount: "500"
            deleteReward:
            - denom: "honey"
              amount: "250"
          - apiary_type: "APIARY"
            space_available: 8
            max_honey: "15"
            price:
            - denom: "honey"
              amount: "900"
            deleteReward:
            - denom: "honey"
              amount: "450"
          - apiary_type: "ALVEARY"
            space_available: 12
            max_honey: "25"
            price:
            - denom: "honey"
              amount: "1500"
            deleteReward:
            - denom: "honey"
              amount: "750"

        bee_types:
          - bee_type: "SMALL_BEE"
            honey_per_hour: "0.55"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1100"
          - bee_type: "BEE"
            honey_per_hour: "0.62"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1200"
          - bee_type: "LUCKY_BEE"
            honey_per_hour: "0.64"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1280"
          - bee_type: "HONEY_BEE"
            honey_per_hour: "0.66"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1370"
          - bee_type: "SKILLED_BEE"
            honey_per_hour: "0.71"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1500"
          - bee_type: "CURIOUS_BEE"
            honey_per_hour: "0.75"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1650"
          - bee_type: "HONEY_EXPLORER"
            honey_per_hour: "0.8"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1780"
          - bee_type: "HONEY_HUNTER"
            honey_per_hour: "0.84"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "1800"
          - bee_type: "WONDER_BEE"
            honey_per_hour: "0.85"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "2100"
          - bee_type: "DIAMOND_STING"
            honey_per_hour: "0.9"
            body_size: 1
            air_dependency: "1"
            air_consume: "0.5"
            price:
            - denom: "honey"
              amount: "2350"