init:
  app:
    minimum-gas-prices: "0.000005honey"
accounts:
  - name: alice
    coins: ["20000honey", "200000000cone"]
  - name: bob
    coins: ["10000honey"]
  - name: bobi
    coins: ["100000honey"]
validator:
  name: alice
  staked: "100000000cone"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5honey", "100000stake"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "cone"
    gov:
      deposit_params:
        min_deposit:
          - denom: "cone"
            amount: "10000"
        max_deposit_period: "172800s"
      voting_params:
        voting_period: "172800s"
    bears:
      params:
        burn_rate: "0.5"
        price_set_name: 
          - denom: "honey"
            amount: "100"
        price_tile: 
          - denom: "honey"
            amount: "100"
        price_tree: 
          - denom: "honey"
            amount: "100"
        reward_tree: 
          - denom: "cone"
            amount: "100"
        price_decoration_flowers: 
          - denom: "honey"
            amount: "100"
        price_decoration_flag: 
          - denom: "honey"
            amount: "150"
        price_decoration_lamp: 
          - denom: "honey"
            amount: "200"
        price_decoration_green_bee: 
          - denom: "honey"
            amount: "500"
        price_decoration_fountain: 
          - denom: "honey"
            amount: "1000"
        apiary_bee_house_params:
          max_count_bees: 5
          max_count_honey: 5
          price:
            - denom: "honey"
              amount: "500"
        apiary_apiary_params:
          max_count_bees: 8
          max_count_honey: 15
          price:
            - denom: "honey"
              amount: "900"
        apiary_alveary_params:
          max_count_bees: 12
          max_count_honey: 25
          price:
            - denom: "honey"
              amount: "1500"