init:
  config:
    consensus:
      timeout_commit: "1s"
  app:
    minimum-gas-prices: "0.000005honey"
accounts:
  - name: alice
    coins: ["20000honey", "200000000cone"]
  - name: bob
    coins: ["10000honey"]
  - name: bobi
    coins: ["100000honey"]
validator:
  name: alice
  staked: "100000000cone"
# client:
#   openapi:
#     path: "docs/static/openapi.yml"
#   vuex:
#     path: "vue/src/store"
# faucet:
#   name: bob
#   coins: ["5honey", "100000stake"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "cone"
    gov:
      deposit_params:
        min_deposit:
          - denom: "cone"
            amount: "10000"
        max_deposit_period: "172800s"
      voting_params:
        voting_period: "172800s"
    bears:
      params:
        burn_rate: "0.5"
        price_set_name: 
          - denom: "honey"
            amount: "100"
        price_tile: 
          - denom: "honey"
            amount: "100"
        price_tree: 
          - denom: "honey"
            amount: "100"
        reward_tree: 
          - denom: "cone"
            amount: "100"

        tree_types:
          - tree_type: OAK
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: SPRUCE
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: APPLE_TREE
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"
          - tree_type: WILLOW
            price:
              - denom: "honey"
                amount: "1500"
            reward:
              - denom: "cone"
                amount: "150"

        decoration_types:
          - decoration_type: "FLOWERS"
            price:
              - denom: "honey"
                amount: "100"
          - decoration_type: "FLAG"
            price:
              - denom: "honey"
                amount: "150"
          - decoration_type: "LAMP"
            price:
              - denom: "honey"
                amount: "200"
          - decoration_type: "GREEN_BEE"
            price:
              - denom: "honey"
                amount: "500" 
          - decoration_type: "FOUNTAIN"
            price:
              - denom: "honey"
                amount: "1000" 
        
        apiary_types:
          - apiary_type: "BEE_HOUSE"
            space_available: 5
            max_honey: 5
            price:
            - denom: "honey"
              amount: "500"
          - apiary_type: "APIARY"
            space_available: 8
            max_honey: 15
            price:
            - denom: "honey"
              amount: "900"
          - apiary_type: "ALVEARY"
            space_available: 12
            max_honey: 25
            price:
            - denom: "honey"
              amount: "1500"

        bee_types:
          - bee_type: "SMALL_BEE"
            honey_per_hour: "0.0001"
            body_size: 1
            oxygen_dependency: "1"
            price:
            - denom: "honey"
              amount: "1100"
          - bee_type: "BEE_2"
            honey_per_hour: "0.0002"
            body_size: 1
            oxygen_dependency: "1"
            price:
            - denom: "honey"
              amount: "1200"

              Small Bee	Bee	Lucky Bee	Honey Bee	Skilled Bee	Curious Bee	Honey Explorer	Honey Hunter	Wonder Bee	Diamond Sting
              1100	1200	1280	1370	1500	1650	1780	1800	2100	2350
1	1	1	1	1	1	1	1	1	1
0.55	0.62	0.64	0.66	0.71	0.75	0.8	0.84	0.85	0.9
1	1	1	1	1	1	1	1	1	1